import React, { useState, useEffect } from "react";
import { Loader, Card } from "../components";
import { url } from "../assets";
const Saved = () => {
  const [loading, setLoading] = useState(false);
  const [savedPosts, setSavedPosts] = useState([]);

  useEffect(() => {
    const fetchPosts = async () => {
      setLoading(true);
      try {
        const response = await fetch(`${url}/api/v1/post/checkedSaved`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${localStorage.getItem("token") ?? null}`,
          },
        });

        if (response.ok) {
          const result = await response.json();

          let arrays = result?.data.map((e) => e.photo_id);
          const response2 = await fetch(`${url}/api/v1/post`, {
            method: "GET",
            headers: {
              "Content-Type": "application/json",
              Authorization: `Bearer ${localStorage.getItem("token") ?? null}`,
            },
          });
          if (response2.ok) {
            const obj = await response2.json();
            setSavedPosts(obj.data.filter((e) => arrays.includes(e._id)));
          }
        }
      } catch (error) {
        alert(error);
      } finally {
        setLoading(false);
      }
    };
    fetchPosts();
  }, []);

  const RenderCards = ({ data, title }) => {
    if (data.length > 0) {
      return data.map((post) => <Card key={post._id} {...post} />);
    }

    return (
      <h2 className="mt-5 font-bold text-[#6449ff] text-xl uppercase">
        {title}
      </h2>
    );
  };

  return (
    <main className="sm:p-8 px-4   w-full bg-[#f9fafe] dark:bg-[#252525] min-h-[calc(100vh - 73px)]">
      <section className="max-w-7xl mx-auto">
        <div>
          <h1 className="font-extrabold text-[#222328] dark:text-white  text-[32px]">
            Saved
          </h1>
          <p className="mt-2 text-[#666475] text-[16px] max-w-[500px]">
            Browser through a collection of imaginative and visually stunning
            images generated by DALL-E AI
          </p>
        </div>

        <div className="mt-10 ">
          {loading ? (
            <div className="flex justify-center items-center">
              <Loader />
            </div>
          ) : (
            <div>
              <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
                <RenderCards data={savedPosts} title="Saved Posts" />
              </div>
            </div>
          )}
        </div>
      </section>
    </main>
  );
};

export default Saved;
